### ISSUE TITLE
testsuite fails on 32-bit

### ISSUE THREAD

**Issue by deep-42-thought** [aubio/aubio#231]
two tests fail on i686 due to rounding errors:
```
======================================================================
FAIL: test_hztomel (tests.test_hztomel.aubio_hztomel_test_case)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/aubio/src/aubio-0.4.8/python/tests/test_hztomel.py", line 19, in test_hztomel
    assert_equal(hztomel(200.), 3.)
  File "/usr/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 414, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 2.9999999329447746
 DESIRED: 3.0

======================================================================
FAIL: test_meltohz (tests.test_hztomel.aubio_hztomel_test_case)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/aubio/src/aubio-0.4.8/python/tests/test_hztomel.py", line 30, in test_meltohz
    assert_equal(meltohz(3.), 200.)
  File "/usr/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 414, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 199.99999237060547
 DESIRED: 200.0

----------------------------------------------------------------------
Ran 595 tests in 1.645s

FAILED (failures=2, skipped=29)
```

IMHO, they should use `assert_almost_equal` instead of `assert_equal`, too - like most of the other tests do already.

**Comment by piem** [comment]
hi @deep-42-thought 

Did you pass any additional flags when compiling aubio? Can you reproduce this with the latest git?

Thanks for reporting,

cheers, piem

**Comment by piem** [comment]
hi @deep-42-thought,

can you provide more info or confirm this is solved with version 0.4.9?

thanks, piem

**Comment by deep-42-thought** [comment]
yes, it still fails with 0.4.9
The instructions used to build are here: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/aubio
I'll test with the current HEAD next

**Comment by deep-42-thought** [comment]
hmm, it looks, like the tarball of the 0.4.9 version contains files additional to the git tag 0.4.9 - where do I find/generate those?

**Comment by piem** [comment]
Hi @deep-42-thought ,

The waf script can be fetched with `make expandwaf`.

Additionally, some files were erroneously shipped in the tarball. You can simply ignore them:
```
-rw-r--r-- root/root        54 2019-02-07 16:59 aubio-0.4.9/aubio-0.4.9.tar.bz2.md5
-rw-r--r-- root/root        62 2019-02-07 17:00 aubio-0.4.9/aubio-0.4.9.tar.bz2.sha1
-rw-r--r-- root/root        86 2019-02-07 17:00 aubio-0.4.9/aubio-0.4.9.tar.bz2.sha256
```
fcc11e9 should prevent this for the next release.

Nothing changed since 0.4.9, so not much to test yet. I'll see if i can reproduce using the arch build script. Thanks for the additional info.

cheers, piem

**Comment by piem** [comment]
I can't seem to reproduce this, but it seems the same tests passed with 0.4.8. ca9d5aa is a good suspect.

@deep-42-thought, do the tests pas for you after applying the reverse patch for ca9d5aa?

    $ git show -p ca9d5aa | git apply -R

**Comment by deep-42-thought** [comment]
When I reverse ca9d5aa, it still fails.
```=================================== FAILURES ===================================
_____________________ aubio_hztomel_test_case.test_hztomel _____________________

self = <test_hztomel.aubio_hztomel_test_case testMethod=test_hztomel>

    def test_hztomel(self):
        assert_equal(hztomel(0.), 0.)
        assert_almost_equal(hztomel(400. / 3.), 2., decimal=5)
        assert_almost_equal(hztomel(1000. / 3), 5.)
>       assert_equal(hztomel(200.), 3.)
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: 2.9999999329447746
E        DESIRED: 3.0

python/tests/test_hztomel.py:20: AssertionError
_____________________ aubio_hztomel_test_case.test_meltohz _____________________

self = <test_hztomel.aubio_hztomel_test_case testMethod=test_meltohz>

    def test_meltohz(self):
        assert_equal(meltohz(0.), 0.)
        assert_almost_equal(meltohz(2), 400. / 3., decimal=4)
>       assert_equal(meltohz(3.), 200.)
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: 199.99999237060547
E        DESIRED: 200.0

python/tests/test_hztomel.py:31: AssertionError
=============== 2 failed, 591 passed, 38 skipped in 3.83 seconds ===============
```
I really believe, this exposes some difference in the (accuracy of) floating point arithmetic on ia32 and x86_64

**Comment by piem** [comment]
hi @deep-42-thought 

I could confirm and reproduce this bug. One way to work around it is to compile `CFLAGS=-ffloat-store`. Not sure how that affects performance.

best, piem

**Comment by piem** [comment]
@deep-42-thought I ended up relaxing the test as you originally suggested.

It would be nice to avoid such rounding errors, but adding `-ffloat-store` would likely affect the performance.

best, piem
